# Generated by Django 5.0.3 on 2024-03-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_for', '0002_book_author_alter_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
