# Generated by Django 5.0.3 on 2024-03-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_for', '0012_alter_department_college_alter_professor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ManyToManyField(to='person_for.college'),
        ),
    ]
