# Generated by Django 5.0.3 on 2024-03-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_for', '0013_alter_department_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ManyToManyField(related_name='departments', to='person_for.college'),
        ),
    ]
