# Generated by Django 5.0.3 on 2024-03-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_for', '0014_alter_department_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ManyToManyField(to='person_for.college'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ManyToManyField(to='person_for.department'),
        ),
    ]
