# Generated by Django 5.0.3 on 2024-03-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_for', '0015_alter_department_college_alter_professor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ManyToManyField(related_name='departments', to='person_for.college'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ManyToManyField(related_name='professors', to='person_for.department'),
        ),
    ]
